#setwd("~/Projects/DFS/resultsAnalysis")
#setwd("~/Documents/PrincetonFall16/fantasyfootball/DFS/")

####### DESCRIPTION #######
# This file is divided into three parts:
# I. We look at a few distributions week over week:
#   (1) Fpts of placing lineups (in resultsAnalysis/data_warehouse/contest_results)
#       - There isn't a noticeable pattern
#   (2) Fpts of our generated lineups (be sure to set the formulation yourself, currently hardcoded)
#       - The max has decreased noticeably since weeks 2-5
# II. We look at the number of fpts scored by the best possible lineups, generated using Actual
#     - 10k lineups generated by form 0/overlap 8/exposure 1 does not score under 1st place. We need to
#       generate a lot more lineups and use a formulation with more constraints (form 4)
# III. We look at the number of unique players that show up in placing lineups (in resultsAnalysis/data_warehouse/contest_results)
#     - Testing theory. Let P = {P_1,...,P_N}, where P is the set of N players s.t. any 9 players of this set
#       sums to 200+ fpts (i.e. earns decent payout). Theory: N is decreasing week over week b/c coaches are
#       finding their most reliable players for the season, and these players get the most touches.


####### IMPORT LIBRARIES #########
library('stringr')
library("emdbook")

####### SET PARAMETERS FOR THIS FILE #########
week.latest <- 15


####### LOAD $20/$27 CONTEST FILES #######
# weeks we have
wks.20 <- c(2:9)
wks.27 <- c(11:week.latest)

# load $20 contest results and payout structure
for (i in wks.20) {
  name <- paste0("contest_1M_results_wk", i)
  assign(name, read.csv(file = paste0("resultsAnalysis/data_warehouse/contest_results/$20_contest_full_results_week", i, ".csv"), stringsAsFactors = F))

  name <- paste0("payout_1M_structure_wk", i)
  assign(name, read.csv(file = paste0("resultsAnalysis/data_warehouse/weekly_payout_structure/$20_payout_structure_week", i, ".csv"), stringsAsFactors = F))
}

# load $27 contest results (as $20 results for naming convention) and payout structure
for (i in wks.27) {
  name <- paste0("contest_1M_results_wk", i)
  assign(name, read.csv(file = paste0("resultsAnalysis/data_warehouse/contest_results/$27_contest_full_results_week", i, ".csv"), stringsAsFactors = F))

  name <- paste0("payout_1M_structure_wk", i)
  assign(name, read.csv(file = paste0("resultsAnalysis/data_warehouse/weekly_payout_structure/$27_payout_structure_week", i, ".csv"), stringsAsFactors = F))
}


####### PART I #######
# (1) Plot histogram of placing lineups fpts
par(mfrow=c(3,4)) # hard coded for now
for (i in c(wks.20, wks.27)) {
  # load dfs
  temp.results <- eval(parse(text=paste0("contest_1M_results_wk", i)))
  temp.payout <- eval(parse(text=paste0("payout_1M_structure_wk", i)))
  
  # subset to placing lineups only
  place.last <- temp.payout$Place_hi[nrow(temp.payout)]
  temp.results <- temp.results[1:place.last,]
  
  # plot histogram
  hist(temp.results$Points, main = paste0("Wk ", i), xlab = paste0("Fpts (min: ", min(temp.results$Points), ", max: ", max(temp.results$Points),")"))
}

# (2) Plot histogram of generated lineups fpts (hard coded dfn_formulation4_overlap_4_exposure_0.4)
par(mfrow=c(3,4)) # hard coded for now
gen.max.vec <- rep(NA, week.latest)
gen.min.vec <- rep(NA, week.latest)
gen.mean.vec <- rep(NA, week.latest)
gen.sd.vec <- rep(NA, week.latest)
for (w in 1:week.latest) {
  if (w %in% c(wks.20, wks.27) & w != 3) {
    # load dfs and clean
    lineups <- read.csv(paste0("resultsAnalysis/data_warehouse/testing_lineups/week", w, "_dfn_FreqInd_formulation4_overlap_4_exposure_0.4.csv")) # set formulation!
    
    # player.performance <- read.csv(file = paste0("resultsAnalysis/data_warehouse/player_weekly_performance/draftkings_player_production_week", w, ".csv"), stringsAsFactors = F)
    # player.performance$Actual.Score[is.na(player.performance$Actual.Score)] <- 0
    # player.performance$Player <- sub(' Sr.','', player.performance$Player)
    # player.performance$Player <- sub(' Jr.','', player.performance$Player)
    
    player.performance <- read.csv(file = paste0('optimizationCode/data_warehouse/dailyfantasynerd/updates/dfn_offense_week', w, ".csv"), stringsAsFactors = F)
    player.performance.def <- read.csv(file = paste0('optimizationCode/data_warehouse/dailyfantasynerd/updates/dfn_defense_week', w, ".csv"), stringsAsFactors = F)
    
    # clean defense names
    temp.def.names <- str_split_fixed(player.performance.def$Player.Name, " ", 3) # split at " "
    for (z in 1:nrow(temp.def.names)) {
      if (temp.def.names[z,3] == "") {
        player.performance.def$Player.Name[z] <- temp.def.names[z,2]
      } else {
        player.performance.def$Player.Name[z] <- temp.def.names[z,3]
      }
    }
    
    player.performance$Actual.FP[is.na(player.performance$Actual.FP)] <- 0 # be careful with this
    player.performance.def$Actual.FP[is.na(player.performance.def$Actual.FP)] <- 0 # be careful with this
    
    # compute fpts
    for (i in 1:ncol(lineups)) {
      lineups[,i] <- substr(lineups[,i], 1, regexpr('\\(', lineups[,i]) - 2)
      lineups[,i] <- sub(' Sr.','', lineups[,i])
      lineups[,i] <- sub(' Jr.','', lineups[,i]) 
    }
    lineups[,ncol(lineups)] <- substr(lineups[,ncol(lineups)], 1, nchar(lineups[,ncol(lineups)])-1)
    
    # total_results <- player.performance[,c('Player', 'Actual.Score')]
    total_results <- player.performance[,c('Player.Name', 'Actual.FP')]
    total_results <- rbind(total_results, player.performance.def[,c('Player.Name', 'Actual.FP')])
    lineups$total <- 0
    
    for (index in 1:nrow(lineups)){
      row <- t(lineups[index,])
      # colnames(row) <- 'Player'
      # row <- merge(row, total_results, by = 'Player')
      # lineups$total[index] <- sum(row$Actual.Score)
      colnames(row) <- 'Player.Name'
      row <- merge(row, total_results, by = 'Player.Name')
      lineups$total[index] <- sum(row$Actual.FP)
    }
    
    # plot histogram
    hist(lineups$total, main = paste0("Wk ", w), xlab = paste0("Fpts (min: ", min(lineups$total), ", max: ", max(lineups$total),")"), xlim = c(50, 270))
    
    # store stats
    gen.max.vec[w] <- max(lineups$total)
    gen.min.vec[w] <- min(lineups$total)
    gen.mean.vec[w] <- mean(lineups$total)
    gen.sd.vec[w] <- sd(lineups$total)
  }
}

# plot max, min, mean, sd
par(mfrow=c(2,2))
plot(gen.mean.vec, type = 'b', xlab = "Week", ylab = "Mean Fpts", main = "Mean Fpts of Form4-Ovrlap4-Exp0.4-FreqInd Lineups")
plot(gen.sd.vec, type = 'b', xlab = "Week", ylab = "SD Fpts", main = "SD Fpts of Form4-Ovrlap4-Exp0.4-FreqInd Lineups")
plot(gen.max.vec, type = 'b', xlab = "Week", ylab = "Max Fpts", main = "Max Fpts of Form4-Ovrlap4-Exp0.4-FreqInd Lineups")
plot(gen.min.vec, type = 'b', xlab = "Week", ylab = "Min Fpts", main = "Min Fpts of Form4-Ovrlap4-Exp0.4-FreqInd Lineups")


####### II. PLOT BEST POSSIBLE LINEUPS GIVEN ACTUAL FPTS #######
par(mfrow=c(3,4)) # hard coded for now
actual.max.vec <- rep(NA, week.latest)
actual.min.vec <- rep(NA, week.latest)
actual.mean.vec <- rep(NA, week.latest)
# actual.median.vec <- rep(NA, week.latest)
actual.sd.vec <- rep(NA, week.latest)
for (i in 2:week.latest) {
  # currently 1000 lineups
  lineups <- read.csv(file = paste0("resultsAnalysis/data_warehouse/testing_lineups/week", i, "_actual_formulation0_overlap_8_exposure_1_numlineups_1000_results.csv"), stringsAsFactors = F)
  plot(sort(lineups$total, decreasing = T), main = paste0("Wk ", i), xlab = paste0("min: ", min(lineups$total), ", max: ", max(lineups$total)), ylab = paste0("Fpts (SD: ", format(round(sd(lineups$total), 2),nsmall = 2), ")"))
  actual.max.vec[i] <- max(lineups$total)
  actual.min.vec[i] <- min(lineups$total)
  actual.mean.vec[i] <- mean(lineups$total)
  # actual.median.vec[i] <- median(lineups$total)
  actual.sd.vec[i] <- sd(lineups$total)
}

# plot max, min, mean, sd
par(mfrow=c(2,2))
plot(actual.mean.vec, type = 'b', xlab = "Week", ylab = "Mean Fpts", main = "Mean Fpts of Top 1000 Lineups Using Actual")
plot(actual.sd.vec, type = 'b', xlab = "Week", ylab = "SD Fpts", main = "SD Fpts of Top 1000 Lineups Using Actual")
plot(actual.max.vec, type = 'b', xlab = "Week", ylab = "Max Fpts", main = "Max Fpts of Top 1000 Lineups Using Actual")
plot(actual.min.vec, type = 'b', xlab = "Week", ylab = "Min Fpts", main = "Min Fpts of Top 1000 Lineups Using Actual")


####### III. PLOT NUMBER OF UNIQUE PLAYERS IN PLACING LINEUPS #######
# cleaning
splitPlayers <- function(x) {
  return(str_split_fixed(x, "QB | RB | WR | TE | FLEX | DST ", 10)[2:10])
}

# note that $20 and $27 games differ. $20: ~250k entries, top ~60k cash out. $27: ~150k entries, top ~40k cash out
thresholds <- floor(lseq(from = 100, to = 100000, 10))
thresholds
num.unique.players <- matrix(NA, nrow = length(thresholds), ncol = week.latest)
rownames(num.unique.players) <- thresholds # label rows (each column is a week)
for (n in 1:length(thresholds)) {
  for (i in 1:week.latest) {
    if (i %in% c(wks.20, wks.27)) {
      temp.results <- eval(parse(text=paste0("contest_1M_results_wk", i)))
      temp.payout <- eval(parse(text=paste0("payout_1M_structure_wk", i)))
      place.last <- temp.payout$Place_hi[nrow(temp.payout)]
      temp.players <- unlist(lapply(X = temp.results$Lineup[1:thresholds[n]], FUN = splitPlayers))
      print(paste0("Threshold Place: ",thresholds[n]," - Week ",i," - Num Unique Players: ",length(unique(temp.players))))
      num.unique.players[n,i] <- length(unique(temp.players)) 
    }
  }
}
num.unique.players
num.unique.players.table <- t(as.table(num.unique.players))

# plot
par(mfrow=c(1,1))
matplot(num.unique.players.table, type = 'b', pch = c('o'), xlab = "Week", ylab = "Num Unique Players", main = "Num Unique Players, Varying Place Threshold")
# legend("bottomleft", colnames(num.unique.players.table),col=seq_len(ncol(num.unique.players.table)), cex=1, fill=seq_len(ncol(num.unique.players.table)))

# Number of games each week (sunday):
num.games <- c(13,14,14,13,12,13,13,11,11,12,12,12,13,14,13) # up to wk 15
num.games <- cbind(1:15, num.games)
colnames(num.games) <- c('Week','Num.Games')
num.games
par(mfrow=c(1,1))
plot(num.games[,1], num.games[,2], type = 'b', xlab = 'Week', ylab = 'Number of Games', main = 'Number of Sunday Games Each Week')

# View place.last for each week (very different between $20 and $27)
# for (i in 1:week.latest) {
#   if (i %in% c(wks.20, wks.27)) {
#     temp.results <- eval(parse(text=paste0("contest_1M_results_wk", i)))
#     temp.payout <- eval(parse(text=paste0("payout_1M_structure_wk", i)))
#     place.last <- temp.payout$Place_hi[nrow(temp.payout)]
#     print(place.last)
#   }
# }


cor.mat <- matrix(data = NA, nrow = nrow(num.unique.players), ncol = 4) # corr of num.unique.players (for each threshold place) vs actual.mean.vec and gen.mean.vec
row.names(cor.mat) <- row.names(num.unique.players)
colnames(cor.mat) <- c("cor w/ actual.mean", "cor w/ gen.mean (form4,FreqInd)", "cor w/ gen.max (form4,FreqInd)", "cor w/ gen.min (form4,FreqInd)")
for (i in 1:nrow(num.unique.players)) {
  cor.mat[i,1] <- round(cor(num.unique.players[i,], actual.mean.vec, use = "complete.obs"),4)
  cor.mat[i,2] <- round(cor(num.unique.players[i,], gen.mean.vec, use = "complete.obs"),4)
  cor.mat[i,3] <- round(cor(num.unique.players[i,], gen.max.vec, use = "complete.obs"),4)
  cor.mat[i,4] <- round(cor(num.unique.players[i,], gen.min.vec, use = "complete.obs"),4)
}
View(cor.mat)
